// Auto-generated from the researched 365-day curriculum outline.
// Source of truth: content/journey/seerah/CURRICULUM_OUTLINE.md
// Do not hand-edit day entries here without updating that file to match.

export interface SeerahPlanDay {
  day: number;
  title: string;
  ref: string;
  note: string;
}

export interface SeerahPlanEra {
  id: number;
  title: string;
  range: string;
  dayStart: number;
  dayEnd: number;
  blurb: string;
  tags: string[];
  days: SeerahPlanDay[];
}

export const SEERAH_PLAN_ERAS: SeerahPlanEra[] = [
  {
    id: 0,
    title: "The First Religion",
    range: "Days 1–10",
    dayStart: 1,
    dayEnd: 10,
    blurb: "Before history as we usually tell it: the Oneness of Allah declared before creation, the first human made khalīfah, the first fall and the first forgiveness — establishing the one truth every prophet after this will simply renew.",
    tags: ["Tawḥīd","Adam","Origins"],
    days: [
      { day: 1, title: "Before Creation", ref: "Q 112:1–4", note: "Al-Ikhlāṣ states the truth that predates the universe: Allah is One, needing nothing, resembling nothing." },
      { day: 2, title: "The Covenant of Every Soul", ref: "Q 7:172", note: "Before any of us were born, every soul testified: \"Am I not your Lord?\" — \"Yes, we testify.\"" },
      { day: 3, title: "The Creation of Adam", ref: "Q 2:30–33", note: "Angels question, Allah teaches Adam the names of all things, and khilāfah — stewardship of the earth — is announced." },
      { day: 4, title: "Iblīs Refuses to Bow", ref: "Q 7:11–18", note: "Pride, not ignorance, is the root of the first rebellion — and the origin of open enmity toward humankind." },
      { day: 5, title: "Adam and Ḥawwā' in the Garden", ref: "Q 2:35–36, 7:19–22", note: "One tree, one instruction, and the whisper that made it feel bigger than it was." },
      { day: 6, title: "The First Tawbah", ref: "Q 2:37, 7:23", note: "\"Our Lord, we have wronged ourselves\" — the words that became every believer's return." },
      { day: 7, title: "Sent Down With a Promise", ref: "Q 20:123–124", note: "\"Whoever follows My guidance will not go astray nor suffer\" — guidance promised before the first footstep on earth." },
      { day: 8, title: "Hābīl and Qābīl", ref: "Q 5:27–31", note: "The first murder, the first grief, and the raven that taught a killer how to bury his brother." },
      { day: 9, title: "Idrīs, the Raised One", ref: "Q 19:56–57, 21:85", note: "Truthful, patient, and raised to \"a high station\" — one of the earliest names in the chain of prophethood." },
      { day: 10, title: "One Message, Many Messengers", ref: "Q 21:25, 16:36", note: "\"We did not send any messenger before you except that We revealed to him: there is no god but Me\" — the thread that ties every day that follows to this first one." },
    ],
  },
  {
    id: 1,
    title: "Prophets Before Ibrahim",
    range: "Days 11–30",
    dayStart: 11,
    dayEnd: 30,
    blurb: "Nūḥ's nine hundred and fifty years of calling, Hūd and Ṣāliḥ confronting nations proud of their own strength, and Lūṭ standing against a city that had lost its shame — the recurring shape of a people forgetting, and mercy that keeps calling anyway.",
    tags: ["Nūḥ","Hūd","Ṣāliḥ","Lūṭ"],
    days: [
      { day: 11, title: "A Nation That Forgot Allah", ref: "Q 71:1", note: "Nūḥ is sent to a people worshipping idols carved with their own hands — Wadd, Suwā', Yaghūth, Ya'ūq, and Nasr." },
      { day: 12, title: "Nine Hundred and Fifty Years of Calling", ref: "Q 29:14", note: "Patience measured not in seasons but in nearly a millennium — dawah with almost no visible fruit." },
      { day: 13, title: "\"I Have Called My People Night and Day\"", ref: "Q 71:5–9", note: "Nūḥ's own account of his method: privately, publicly, every way he knew — and still mostly refused." },
      { day: 14, title: "Build the Ark", ref: "Q 11:37–38", note: "Obedience to a command that made no sense yet — built on dry land, mocked by everyone watching." },
      { day: 15, title: "The Skies Are Opened", ref: "Q 54:11–12", note: "Rain from above and springs from below meet by design, not accident." },
      { day: 16, title: "\"O My Son, Embark With Us\"", ref: "Q 11:42–43", note: "A father's plea refused — kinship without faith could not board the ark of safety." },
      { day: 17, title: "The Ark Comes to Rest", ref: "Q 11:44", note: "\"O earth, swallow your water... and it rested on al-Jūdī\" — the flood ends in a single verse of total command." },
      { day: 18, title: "A New Beginning", ref: "Q 71:26–28", note: "Nūḥ's prayer for the believers who remain — humanity restarts through a remnant, not a majority." },
      { day: 19, title: "Hūd and the People of 'Ād", ref: "Q 7:65–72", note: "A people renowned for physical strength and monumental building, certain their power made them exempt." },
      { day: 20, title: "\"We Will Not Leave Our Gods for Your Words\"", ref: "Q 46:21–26", note: "Arrogance answered by a barren, howling wind — three days that undid generations of pride." },
      { day: 21, title: "Ṣāliḥ and the She-Camel", ref: "Q 7:73–79", note: "Thamūd, carvers of homes into mountains, given a living sign they were forbidden to harm." },
      { day: 22, title: "The Camel Is Hamstrung", ref: "Q 91:11–15", note: "Impatience with a boundary — and the Ṣayḥah, one terrible cry, that answered it." },
      { day: 23, title: "Ruins as Reminders", ref: "Q 27:52", note: "What was left of 'Ād and Thamūd stood as a visible lesson for the very people who told their story next." },
      { day: 24, title: "The Pattern of Denial", ref: "Q 23:44", note: "\"Every time a messenger came to a nation, they denied him\" — a pattern the Qur'an names openly, not hides." },
      { day: 25, title: "Mercy Even in Warning", ref: "Q 11:117", note: "\"Your Lord would not destroy the towns unjustly while their people were reformers\" — punishment was never Allah's first choice." },
      { day: 26, title: "Lūṭ and the City That Lost Its Shame", ref: "Q 7:80–84", note: "A prophet living among his own in-laws' city, calling to basic human decency and being mocked for it." },
      { day: 27, title: "Two Guests Lūṭ Did Not Recognize", ref: "Q 15:61–66", note: "Angels arrive as travelers; Lūṭ's distress for their safety reveals how far the city had fallen." },
      { day: 28, title: "A City Overturned", ref: "Q 11:82–83", note: "Marked stones \"not far from the wrongdoers\" — a lesson later caravans, and later readers, would pass by." },
      { day: 29, title: "Lūṭ's Wife", ref: "Q 66:10", note: "A warning that living beside a prophet does not save anyone without their own belief." },
      { day: 30, title: "What These Stories Are For", ref: "Q 12:111", note: "\"There is certainly a lesson in their stories for people of understanding\" — closing the first arc of denial and mercy." },
    ],
  },
  {
    id: 2,
    title: "Ibrahim, Father of Prophets",
    range: "Days 31–60",
    dayStart: 31,
    dayEnd: 60,
    blurb: "From an idol-carver's household to \"Khalīlullāh,\" the Friend of Allah: the fire that would not burn him, the wife and infant son left in an empty valley on trust alone, the well that answered that trust, the House they raised together, and the sacrifice that gave the whole Ummah a annual reminder of submission.",
    tags: ["Ibrāhīm","Ismā'īl","Kaʿbah","Zamzam"],
    days: [
      { day: 31, title: "Born Into a House of Idols", ref: "Q 6:74", note: "Āzar the idol-carver's household — the world Ibrāhīm was raised in and would be the first to question." },
      { day: 32, title: "Looking at the Stars", ref: "Q 6:75–79", note: "A star, a moon, a sun — each admired, then rejected: \"I do not love things that set.\"" },
      { day: 33, title: "\"Do You Worship What You Carve?\"", ref: "Q 37:95–96", note: "Confronting his own people and father directly about objects that can neither harm nor help." },
      { day: 34, title: "The Idols Are Broken", ref: "Q 21:57–58", note: "All but the largest — left deliberately, to make his people ask their own question." },
      { day: 35, title: "\"Ask Them, If They Can Speak\"", ref: "Q 21:62–67", note: "Ibrāhīm turns the town's own logic back on them in front of a gathered crowd." },
      { day: 36, title: "Thrown Into the Fire", ref: "Q 21:68–69", note: "\"O fire, be coolness and safety upon Ibrāhīm\" — a punishment turned, by one word from Allah, into nothing." },
      { day: 37, title: "Emerging Unharmed", ref: "Q 29:24", note: "\"In that is a sign for people who believe\" — the fire remembered less than the faith that survived it." },
      { day: 38, title: "Debating a Tyrant", ref: "Q 2:258", note: "A king who claimed power over life and death is answered with a simple demand about the sun's direction." },
      { day: 39, title: "Leaving Home for Allah's Sake", ref: "Q 29:26", note: "\"I am emigrating to my Lord\" — the first hijrah in this story, chosen before it was ever commanded." },
      { day: 40, title: "A Prayer for Righteous Offspring", ref: "Q 37:100", note: "\"My Lord, grant me one of the righteous\" — a du'ā' that will shape everything that follows." },
      { day: 41, title: "Glad Tidings of Ismā'īl", ref: "Q 37:101", note: "\"A forbearing boy\" — the son whose own submission will one day be tested." },
      { day: 42, title: "Left in an Empty Valley", ref: "Q 14:37", note: "Hājar and infant Ismā'īl settled in a barren valley with no visible water, by direct command." },
      { day: 43, title: "\"Did Allah Command You to This?\"", ref: "Ḥadīth (Bukhārī)", note: "Hājar's question, and her own answer: \"Then He will not leave us to be lost.\"" },
      { day: 44, title: "The Running Between Ṣafā and Marwah", ref: "Ḥadīth (Bukhārī)", note: "Seven desperate crossings searching for any sign of water or another human being." },
      { day: 45, title: "Zamzam Springs Forth", ref: "Ḥadīth (Bukhārī)", note: "Beneath an infant's kicking heel, mercy answers a trust that had nothing left to stand on but Allah." },
      { day: 46, title: "A Settlement Grows", ref: "Seerah", note: "The tribe of Jurhum, drawn by the water, settles beside Hājar and Ismā'īl — a lone family becomes a town." },
      { day: 47, title: "Ibrāhīm Returns to the Valley", ref: "Seerah", note: "Visits across the years to the family he had left entirely in Allah's care." },
      { day: 48, title: "Raising the Foundations of the House", ref: "Q 2:127", note: "Father and grown son build together — the Ka'bah rises as a shared act of worship, not a solitary one." },
      { day: 49, title: "\"Our Lord, Accept This From Us\"", ref: "Q 2:127–129", note: "A du'ā' for acceptance, and for a future messenger \"from among them\" — heard some 2,500 years later." },
      { day: 50, title: "The Station of Ibrāhīm", ref: "Q 2:125", note: "A single footprint preserved as a place of prayer, still standing beside the House today." },
      { day: 51, title: "Guests Ibrāhīm Did Not Recognize", ref: "Q 51:24–30", note: "Angels arrive as strangers, bringing news of a son, Isḥāq, that surprises even Sārah." },
      { day: 52, title: "Sārah's Laughter", ref: "Q 11:71–73", note: "Glad tidings met with astonishment: \"Shall I bear a child while I am an old woman?\"" },
      { day: 53, title: "Ibrāhīm Pleads for Lūṭ's People", ref: "Q 11:74–76", note: "Compassion extended even toward a city already judged, until told clearly the matter was settled." },
      { day: 54, title: "The Dream of Sacrifice", ref: "Q 37:102", note: "\"I see in a dream that I am sacrificing you\" — and Ibrāhīm asks his son's view rather than simply commanding him." },
      { day: 55, title: "\"Father, Do As You Are Commanded\"", ref: "Q 37:102", note: "Ismā'īl's own submission, offered with a request only for patience, not rescue." },
      { day: 56, title: "The Ram of Mercy", ref: "Q 37:107", note: "\"We ransomed him with a great sacrifice\" — the test proven, and the sacrifice itself made unnecessary." },
      { day: 57, title: "Why the Sacrifice Continues Today", ref: "Q 22:37", note: "\"It is not their meat or blood that reaches Allah, but the piety from you\" — the ritual explained plainly." },
      { day: 58, title: "Isḥāq and Ya'qūb", ref: "Q 21:72", note: "\"We gave him Isḥāq and Ya'qūb, all as an increase\" — the blessed lineage widens." },
      { day: 59, title: "Ibrāhīm's Final Prayer", ref: "Q 14:35–41", note: "For his own household, for future generations, and for the parents who never believed." },
      { day: 60, title: "Khalīlullāh — the Friend of Allah", ref: "Q 4:125", note: "A title given to no one else — closing the arc that shaped the family history for everything still to come." },
    ],
  },
  {
    id: 3,
    title: "Yusuf — The Best of Stories",
    range: "Days 61–75",
    dayStart: 61,
    dayEnd: 75,
    blurb: "Sūrah Yūsuf calls itself \"the best of stories,\" and it is told here exactly as it unfolds in the Qur'an: one continuous narrative of betrayal, slavery, false accusation, imprisonment, power, and a forgiveness so complete it closes every wound it opens.",
    tags: ["Yūsuf","Ya'qūb","Miṣr"],
    days: [
      { day: 61, title: "The Dream of Eleven Stars", ref: "Q 12:4–6", note: "A child's dream, and a father's immediate instinct to protect him from what it might provoke." },
      { day: 62, title: "\"Do Not Tell Your Brothers\"", ref: "Q 12:5", note: "Ya'qūb's early warning about Shayṭān's role in human envy — wisdom offered before harm, not after." },
      { day: 63, title: "Jealousy Takes Root", ref: "Q 12:8–10", note: "The brothers' private conversation reveals how far resentment had already traveled." },
      { day: 64, title: "Thrown Into the Well", ref: "Q 12:15", note: "Even here, the first divine reassurance: \"You will surely inform them of this deed of theirs, and they will not know.\"" },
      { day: 65, title: "Sold for a Small Price", ref: "Q 12:19–20", note: "A caravan's passing turns catastrophe into a doorway toward Egypt — unseen by everyone involved." },
      { day: 66, title: "Trusted in the House of al-'Azīz", ref: "Q 12:21–23", note: "Integrity tested inside the very household that had taken him in as property." },
      { day: 67, title: "\"I Seek Refuge in Allah\"", ref: "Q 12:23–24", note: "Temptation refused not through willpower alone, but through remembrance in the moment itself." },
      { day: 68, title: "Imprisoned Though Innocent", ref: "Q 12:33–35", note: "\"Prison is more beloved to me than what they call me to\" — choosing hardship over sin, deliberately." },
      { day: 69, title: "Calling to Tawḥīd From a Cell", ref: "Q 12:37–40", note: "Da'wah continues even here: \"Are separate lords better, or Allah, the One, the Overpowering?\"" },
      { day: 70, title: "Interpreting the King's Dream", ref: "Q 12:43–49", note: "Seven years of plenty, seven of famine — foresight offered freely, still from inside a prison." },
      { day: 71, title: "\"Place Me in Charge of the Storehouses\"", ref: "Q 12:54–57", note: "A request for responsibility, not release — competence recognized where character had already been proven." },
      { day: 72, title: "The Brothers Return, Unknowing", ref: "Q 12:58–62", note: "Years later, hunger brings them face to face with the brother they had sold, and did not recognize." },
      { day: 73, title: "The Cup in Binyāmīn's Bag", ref: "Q 12:70–79", note: "A gentle test, designed to keep his full brother near without yet revealing anything." },
      { day: 74, title: "\"I Am Yūsuf, and This Is My Brother\"", ref: "Q 12:90", note: "The reveal, and immediately: \"No blame will there be upon you today.\"" },
      { day: 75, title: "Ya'qūb's Sight Restored", ref: "Q 12:93–100", note: "\"Truly, I know from Allah what you do not know\" — the story closes exactly where it opened, with a father's love." },
    ],
  },
  {
    id: 4,
    title: "Musa and Bani Isra'il",
    range: "Days 76–110",
    dayStart: 76,
    dayEnd: 110,
    blurb: "No prophet is mentioned more often in the Qur'an than Mūsā. A palace-raised fugitive becomes the one who confronts the most powerful man on earth — and then spends the rest of his life patiently, exhaustedly, mercifully leading a nation that kept forgetting what it had just seen.",
    tags: ["Mūsā","Fir'awn","Banī Isrā'īl"],
    days: [
      { day: 76, title: "A Pharaoh Who Called Himself Lord", ref: "Q 28:4", note: "Systematic oppression of Banī Isrā'īl begins under a ruler who \"exalted himself in the land.\"" },
      { day: 77, title: "Cast Into the River", ref: "Q 28:7", note: "\"Do not fear and do not grieve; We will return him to you\" — an infant sent toward the very palace that threatened him." },
      { day: 78, title: "Raised in Fir'awn's House", ref: "Q 28:8–9", note: "Divine plan hidden inside apparent danger — safety found in the last place anyone would expect it." },
      { day: 79, title: "A Mother's Heart Kept Firm", ref: "Q 28:10", note: "\"We tied firmness to her heart\" — a promise honored even through the hardest waiting." },
      { day: 80, title: "Flight to Madyan", ref: "Q 28:15–21", note: "An accidental death, sudden danger, and Mūsā leaves Egypt with nothing but the clothes on his back." },
      { day: 81, title: "Drawing Water for Two Strangers", ref: "Q 28:23–24", note: "\"My Lord, I am in need of whatever good You send down to me\" — a prayer said with total humility." },
      { day: 82, title: "Ten Years in Madyan", ref: "Q 28:27–28", note: "Marriage into Shu'ayb's family, and a decade of quiet, honest work before the mission ever begins." },
      { day: 83, title: "The Fire at Mount Ṭūr", ref: "Q 20:9–14", note: "\"Indeed, I am your Lord, so remove your sandals\" — the ground itself made sacred by the moment." },
      { day: 84, title: "\"Remove Your Sandals\"", ref: "Q 20:12", note: "A small physical instruction carrying the weight of the encounter about to happen." },
      { day: 85, title: "The Staff Becomes a Serpent", ref: "Q 20:17–21", note: "The first sign given directly to Mūsā, before he is ever asked to show it to anyone else." },
      { day: 86, title: "\"Go to Fir'awn — He Has Transgressed\"", ref: "Q 20:24, 43", note: "The mission is named plainly, aimed at the single most powerful man Mūsā could face." },
      { day: 87, title: "\"Speak to Him Gently\"", ref: "Q 20:44", note: "Even toward a tyrant, the method commanded is softness — \"so that he may be reminded or fear.\"" },
      { day: 88, title: "Hārūn Sent as Support", ref: "Q 20:29–32", note: "\"Strengthen me through my brother\" — Mūsā asks for partnership, not to carry it alone." },
      { day: 89, title: "Facing Fir'awn's Court", ref: "Q 26:23–30", note: "\"And what is the Lord of the worlds?\" — the confrontation begins with a question about who God even is." },
      { day: 90, title: "The Magicians' Challenge", ref: "Q 26:38–40", note: "Egypt's most skilled sorcerers summoned to settle the matter by public spectacle." },
      { day: 91, title: "Ropes and Staffs, Illusion and Truth", ref: "Q 20:65–69", note: "\"What you have brought is trickery\" — and then a single true sign swallows every illusion." },
      { day: 92, title: "The Magicians Prostrate", ref: "Q 20:70–73", note: "Belief overtakes fear of Fir'awn instantly — \"We believe in the Lord of Hārūn and Mūsā.\"" },
      { day: 93, title: "Nine Signs Sent", ref: "Q 17:101", note: "Drought, floods, locusts, lice, frogs, and blood — repeated mercy disguised as repeated warning." },
      { day: 94, title: "\"Let My People Go\"", ref: "Q 20:47", note: "The demand restated again and again, and refused again and again." },
      { day: 95, title: "Leaving Egypt by Night", ref: "Q 26:52–53", note: "A quiet exodus, and Fir'awn's army mobilized to follow before dawn." },
      { day: 96, title: "Trapped at the Sea", ref: "Q 26:61", note: "\"We are surely to be overtaken\" — the companions' fear at the worst possible moment." },
      { day: 97, title: "\"My Lord Is With Me — He Will Guide Me\"", ref: "Q 26:62", note: "Certainty spoken aloud in the narrowest, most hopeless-looking moment of the whole story." },
      { day: 98, title: "The Sea Splits", ref: "Q 26:63", note: "Twelve paths opened, one for each tribe, walking through what should have been impossible." },
      { day: 99, title: "Fir'awn's End", ref: "Q 10:90–92", note: "\"Now?\" — belief offered too late, and a body preserved \"as a sign for those who come after.\"" },
      { day: 100, title: "Gratitude, Then Forgetfulness", ref: "Q 2:51", note: "Forty nights appointed at the mountain begin — and the test of what a freed people do next." },
      { day: 101, title: "The Tablets Given", ref: "Q 7:145", note: "Commandments handed down for a nation still learning what it means to be free." },
      { day: 102, title: "The Golden Calf", ref: "Q 20:85–88", note: "Impatience, in Mūsā's brief absence, turns a people who had just seen the sea split back toward idolatry." },
      { day: 103, title: "Mūsā's Anger and Return", ref: "Q 7:150–151", note: "Confronting Hārūn first, then the people — grief at how quickly the lesson was lost." },
      { day: 104, title: "\"You Will Never See Me — But Look at the Mountain\"", ref: "Q 7:143", note: "The limits of what sight can hold, and the mountain that could not bear what Mūsā asked to witness." },
      { day: 105, title: "The Cloud and the Manna", ref: "Q 2:57", note: "Shade and food provided daily in the wilderness — provision that required no farming, only trust." },
      { day: 106, title: "\"Enter the Land — Do Not Turn Back\"", ref: "Q 5:20–26", note: "Fear of the land's inhabitants leads to refusal, and forty years of wandering as its consequence." },
      { day: 107, title: "Qārūn's Pride and Downfall", ref: "Q 28:76–82", note: "Immense wealth, and the arrogance that convinced him he had earned it alone." },
      { day: 108, title: "The Cow of Banī Isrā'īl", ref: "Q 2:67–73", note: "A strange command met with endless questions — obedience delayed until almost impossible." },
      { day: 109, title: "Al-Khiḍr and the Limits of Knowledge", ref: "Q 18:60–82", note: "Mūsā, the greatest prophet-teacher of his age, learns there is knowledge beyond even his own." },
      { day: 110, title: "What This Nation Teaches Every Believer", ref: "Q 2:83–86", note: "A covenant made, broken, and mercifully renewed again and again — closing the longest arc of this journey." },
    ],
  },
  {
    id: 5,
    title: "Dawud and Sulaiman",
    range: "Days 111–125",
    dayStart: 111,
    dayEnd: 125,
    blurb: "A shepherd boy who kills a giant becomes a prophet-king whose voice the mountains themselves answer in worship, and a son who commands wind and jinn learns that gratitude, not power, is what a throne is actually for.",
    tags: ["Dāwūd","Sulaymān","Bilqīs"],
    days: [
      { day: 111, title: "A Shepherd Boy Faces a Giant", ref: "Q 2:251", note: "Dāwūd and Jālūt (Goliath) — the underdog victory that begins his rise." },
      { day: 112, title: "Kingship and Wisdom", ref: "Q 2:251", note: "\"Allah gave him the kingship and prophethood\" — two things rarely combined in one person." },
      { day: 113, title: "Mountains and Birds Glorify With Him", ref: "Q 34:10, 38:18–19", note: "All of creation, not just human followers, joins Dāwūd's remembrance of Allah." },
      { day: 114, title: "Iron Softened in His Hands", ref: "Q 34:10–11", note: "A craft given as a gift — armor made for protection, credited openly to gratitude, not skill alone." },
      { day: 115, title: "The Zabūr Revealed", ref: "Q 4:163, 17:55", note: "A scripture of praise, given as this era's renewal of the same original message." },
      { day: 116, title: "Two Litigants Test His Judgment", ref: "Q 38:21–25", note: "A parable presented to catch him off guard — and Dāwūd immediately turns the lesson on himself." },
      { day: 117, title: "\"Judge Among People in Truth\"", ref: "Q 38:26", note: "Justice framed as a trust carried, not a privilege enjoyed." },
      { day: 118, title: "Sulaymān Inherits Prophethood", ref: "Q 27:16", note: "\"We have been taught the speech of birds\" — gratitude stated before any boast of power." },
      { day: 119, title: "Commanding Wind and Jinn", ref: "Q 21:81–82, 34:12", note: "A kingdom unlike any given before or after, entirely by Allah's permission." },
      { day: 120, title: "Reviewing His Cavalry", ref: "Q 38:31–33", note: "Love of fine horses catches him distracted from remembrance — and he corrects course immediately." },
      { day: 121, title: "The Ant's Warning", ref: "Q 27:18–19", note: "Sulaymān smiles, grateful that Allah let him understand even the smallest creature's voice." },
      { day: 122, title: "The Hoopoe's Report", ref: "Q 27:20–26", note: "News of a queen who rules a great kingdom yet worships the sun instead of its Creator." },
      { day: 123, title: "A Letter to Bilqīs", ref: "Q 27:28–31", note: "Da'wah conducted through diplomacy and an open invitation, not through force." },
      { day: 124, title: "Her Throne Brought in a Blink", ref: "Q 27:38–40", note: "A sign meant to unsettle pride gently, not humiliate it." },
      { day: 125, title: "\"This Is From the Favor of My Lord\"", ref: "Q 27:40, 44", note: "Bilqīs submits to Allah alongside Sulaymān — closing the arc with a queen's own free testimony." },
    ],
  },
  {
    id: 6,
    title: "The Later Prophets",
    range: "Days 126–150",
    dayStart: 126,
    dayEnd: 150,
    blurb: "Ayyūb's patience through total loss, Yūnus in the belly of the whale, Ilyās and al-Yasa' and Dhul-Kifl standing firm, and finally the family of 'Imrān — Zakariyyā, Yaḥyā, Maryam, and 'Īsā — the last names before the line of prophethood falls silent for centuries.",
    tags: ["Ayyūb","Yūnus","Maryam","'Īsā"],
    days: [
      { day: 126, title: "Ayyūb's Total Test", ref: "Q 21:83", note: "Wealth, health, and family all removed, and still: \"Affliction has touched me, and You are the Most Merciful of the merciful.\"" },
      { day: 127, title: "Patience Without Complaint", ref: "Q 38:41–44", note: "Suffering carried with dignity, addressed to Allah alone rather than performed for others." },
      { day: 128, title: "Healing and Restoration", ref: "Q 21:84", note: "\"We removed what afflicted him and gave him his family, and the like thereof with them.\"" },
      { day: 129, title: "Shu'ayb and the People of Madyan", ref: "Q 7:85", note: "A prophet whose central call is honest business — fairness treated as a matter of faith, not just ethics." },
      { day: 130, title: "\"Do Not Decrease People's Due\"", ref: "Q 11:84–86", note: "Full measure and honest scales commanded as acts of worship." },
      { day: 131, title: "Rejected, Then Overtaken", ref: "Q 26:189", note: "The \"Day of the Shadow\" — punishment following the same pattern seen since Nūḥ." },
      { day: 132, title: "Yūnus Leaves His People in Anger", ref: "Q 21:87", note: "Departing without permission — the one lapse recorded of an otherwise devoted prophet." },
      { day: 133, title: "Swallowed by the Whale", ref: "Q 37:142", note: "Darkness of the sea, the fish, and the night, layered one inside another." },
      { day: 134, title: "\"There Is No God but You\"", ref: "Q 21:87", note: "The du'ā' from inside the fish — brief, complete, and answered." },
      { day: 135, title: "A Nation Spared by Its Own Repentance", ref: "Q 10:98, 37:147–148", note: "The one town in this whole history whose collective repentance arrived in time." },
      { day: 136, title: "Ilyās Confronts Idolatry Among His Own", ref: "Q 37:123–132", note: "\"Do you call upon Ba'l and leave the best of creators?\" — challenging a family religion, not a foreign one." },
      { day: 137, title: "Al-Yasa' and Dhū'l-Kifl", ref: "Q 6:86, 21:85–86", note: "Named briefly, honored equally — \"each was of the righteous\" and \"of the patient.\"" },
      { day: 138, title: "Zakariyyā's Quiet Prayer in Old Age", ref: "Q 19:2–6", note: "\"Do not leave me without an heir\" — asked privately, gently, without demanding a sign." },
      { day: 139, title: "\"We Gave Him Yaḥyā\"", ref: "Q 19:7–8", note: "A name chosen by Allah Himself, given to no one before him." },
      { day: 140, title: "Yaḥyā's Character", ref: "Q 19:12–14", note: "Wisdom while still a child, tenderness, and righteousness described as innate gifts." },
      { day: 141, title: "Zakariyyā's Sign", ref: "Q 19:10", note: "Three days unable to speak except through gesture — a sign held quietly, not announced." },
      { day: 142, title: "Maryam's Upbringing in the Sanctuary", ref: "Q 3:35–37", note: "Raised under Zakariyyā's care after her mother's vow dedicates her before birth." },
      { day: 143, title: "Provision From Nowhere Explainable", ref: "Q 3:37", note: "\"From where does this come to you?\" — \"From Allah\" — Zakariyyā's own faith deepened by what he witnesses in her." },
      { day: 144, title: "The Angel's Announcement", ref: "Q 19:16–21", note: "\"A pure boy\" — news met with plain, honest astonishment, not disbelief." },
      { day: 145, title: "Labor Beneath the Palm Tree", ref: "Q 19:22–26", note: "Solitude, pain, and provision arriving together in the same isolated moment." },
      { day: 146, title: "\"How Can I Speak to One Who Was in the Cradle?\"", ref: "Q 19:27–33", note: "'Īsā's first words, spoken as an infant, answer every accusation before it can even be finished." },
      { day: 147, title: "Miracles by Allah's Permission", ref: "Q 3:49, 5:110", note: "Healing, shaping clay birds, giving life — every single miracle attributed explicitly to \"Allah's leave.\"" },
      { day: 148, title: "The Disciples and the Table Spread", ref: "Q 5:111–115", note: "Trust requested from the disciples, and answered with provision from the heavens." },
      { day: 149, title: "Raised, Not Crucified", ref: "Q 4:157–158", note: "\"They did not kill him, nor crucify him... rather, Allah raised him to Himself\" — the Qur'an's direct correction of the claim." },
      { day: 150, title: "'Īsā's Own Testimony on Judgment Day", ref: "Q 5:116–117", note: "\"I only said what You commanded me\" — closing the line of Banī Isrā'īl's prophets in his own words." },
    ],
  },
  {
    id: 7,
    title: "Jahiliyyah: The World Waiting",
    range: "Days 151–165",
    dayStart: 151,
    dayEnd: 165,
    blurb: "A long gap without a new messenger, and Arabia drifts: three hundred sixty idols around a House built for One God, buried daughters, tribal pride — while two empires spend themselves in endless war, unaware that the next revelation is about to arrive in the last place either expected.",
    tags: ["Makkah","Quraysh","Pre-Islamic Arabia"],
    days: [
      { day: 151, title: "The Long Gap Between Messengers", ref: "Q 5:19", note: "A fatrah — centuries without a new prophet — leading directly into the setting of the next era." },
      { day: 152, title: "The Sacred House Falls Into Idolatry", ref: "Seerah / Ibn Kathīr", note: "Some three hundred sixty idols surround a House Ibrāhīm and Ismā'īl built for the One God alone." },
      { day: 153, title: "The Keepers of the Kaʿbah", ref: "Seerah", note: "Quraysh's guardianship of the House becomes a source of tribal pride, only loosely tied to its original purpose." },
      { day: 154, title: "Tribes, Blood, and Honor", ref: "Seerah", note: "The social fabric that will both resist and, later, carry the message: fierce loyalty, fierce feuds." },
      { day: 155, title: "The Buried Daughters", ref: "Q 81:8–9, 16:58–59", note: "Female infanticide named and condemned directly — one of the clearest moral failures the coming revelation will end." },
      { day: 156, title: "Poets, Markets, and the Power of Words", ref: "Seerah", note: "Sūq 'Ukāẓ and a culture that prized eloquence above almost everything else — soon to meet its match." },
      { day: 157, title: "The Year of the Elephant", ref: "Q 105:1–5", note: "Abraha's army marches on the Kaʿbah and is destroyed by birds and stones — Sūrah al-Fīl's setting." },
      { day: 158, title: "Zamzam Rediscovered", ref: "Seerah", note: "'Abd al-Muṭṭalib uncovers the buried well — Ibrāhīm's legacy resurfacing at the edge of this new era." },
      { day: 159, title: "The Family Line Narrows", ref: "Seerah", note: "Hāshim, 'Abd al-Muṭṭalib, 'Abdullāh — the specific household this story is about to center on." },
      { day: 160, title: "A Handful of Believers Before Islam", ref: "Seerah", note: "The Ḥunafā' — individuals who had already rejected idolatry, searching for the religion of Ibrāhīm." },
      { day: 161, title: "Rome and Persia, the Two Empires", ref: "Seerah / Q 30:1–5", note: "The wider world Arabia sits between — Sūrah ar-Rūm's setting, superpowers exhausting each other." },
      { day: 162, title: "Scriptures That Foretold a Coming Prophet", ref: "Q 7:157, 61:6", note: "Some among the People of the Book were, by their own texts, already watching for him." },
      { day: 163, title: "Trade Routes and the Rhythm of Meccan Life", ref: "Q 106:1–4", note: "Sūrah Quraysh — winter and summer caravans, and the security Makkah depended on without always acknowledging its source." },
      { day: 164, title: "A World Waiting, Whether It Knew It or Not", ref: "Q 3:164", note: "\"Allah conferred favor upon the believers by sending among them a Messenger\" — read here as the promise about to be kept." },
      { day: 165, title: "The Stage Is Set", ref: "Seerah", note: "Everything in this era converges on one house, one family, and one year — closing the last day before the story turns personal." },
    ],
  },
  {
    id: 8,
    title: "Makkah — Birth to Hijrah",
    range: "Days 166–228",
    dayStart: 166,
    dayEnd: 228,
    blurb: "Fifty-three years: an orphan raised by a grandfather and then an uncle, known across Makkah as al-Amīn before a single verse was revealed, then thirteen years carrying a message that cost him almost everything he had — until the night staying was no longer possible.",
    tags: ["Sīrah","Makkah","Revelation"],
    days: [
      { day: 166, title: "The Year of the Elephant, Revisited", ref: "Seerah", note: "Born in Rabī' al-Awwal, in the same year Abraha's army was destroyed — a birth framed by an earlier sign." },
      { day: 167, title: "Born an Orphan", ref: "Seerah", note: "His father 'Abdullāh dies before his birth — loss present from the very first page of his life." },
      { day: 168, title: "Ḥalīmah al-Sa'diyyah and the Desert Years", ref: "Seerah", note: "Nursed and raised among Banū Sa'd; blessing follows the household that takes him in." },
      { day: 169, title: "The Splitting of the Chest", ref: "Ḥadīth (Muslim)", note: "A purification given while still a child, long before revelation, prepared for what was still ahead." },
      { day: 170, title: "His Mother Āminah's Death", ref: "Seerah", note: "Orphaned a second time by age six, on the road back from visiting his father's grave." },
      { day: 171, title: "Under His Grandfather's Wing", ref: "Seerah", note: "'Abd al-Muṭṭalib's particular tenderness toward him, and then his own death two years later." },
      { day: 172, title: "Raised by Abū Ṭālib", ref: "Seerah", note: "An uncle's steady protection, offered without ever sharing his nephew's coming faith." },
      { day: 173, title: "The Journey to Syria and Baḥīrā the Monk", ref: "Seerah", note: "A trading caravan, a monk who recognizes a sign, and a warning quietly given to Abū Ṭālib." },
      { day: 174, title: "Known as al-Amīn — the Trustworthy", ref: "Seerah", note: "A reputation for honesty built years before revelation, later impossible for his opponents to deny." },
      { day: 175, title: "The Sacrilegious War and Ḥilf al-Fuḍūl", ref: "Seerah", note: "Present at conflict as a young man, then part of a pact to defend the wronged — justice instinct before prophethood." },
      { day: 176, title: "Marriage to Khadījah", ref: "Seerah", note: "Fifteen years his senior, a successful businesswoman, and the first human being to believe in him." },
      { day: 177, title: "Rebuilding the Kaʿbah and the Wisdom of Forty", ref: "Seerah", note: "A cloth-and-consensus solution to a dispute over the Black Stone, at the edge of prophethood." },
      { day: 178, title: "A Habit of Withdrawal", ref: "Seerah", note: "Regular retreats to Cave Ḥirā', searching for something Makkah's idols could not give him." },
      { day: 179, title: "\"Read\"", ref: "Q 96:1–5", note: "The night everything changes — the first command of revelation, and its first five verses." },
      { day: 180, title: "Trembling, and Khadījah's Reassurance", ref: "Seerah (Bukhārī)", note: "\"Allah would never disgrace you\" — the first words spoken back to him about who he now was." },
      { day: 181, title: "Waraqah ibn Nawfal's Recognition", ref: "Seerah", note: "\"This is the same Nāmūs that came to Mūsā\" — an elderly scholar names what has just happened." },
      { day: 182, title: "The Pause in Revelation", ref: "Q 93:1–5", note: "Sūrah aḍ-Ḍuḥā answers a fear of abandonment with direct, personal comfort." },
      { day: 183, title: "\"Arise and Warn\"", ref: "Q 74:1–7", note: "Revelation resumes, and the mission is formally, publicly commanded to begin." },
      { day: 184, title: "The First Believers", ref: "Seerah", note: "Khadījah, 'Alī, Abū Bakr, and Zayd ibn Ḥārithah — the earliest circle, each from a different position in life." },
      { day: 185, title: "Three Years of Quiet Da'wah", ref: "Seerah", note: "Trust built privately, one relationship at a time, before any public announcement." },
      { day: 186, title: "Abū Bakr's Circle", ref: "Seerah", note: "'Uthmān, az-Zubayr, 'Abd ar-Raḥmān ibn 'Awf, Sa'd, and Ṭalḥah embrace Islam through his effort." },
      { day: 187, title: "\"Warn Your Closest Kindred\"", ref: "Q 26:214", note: "Da'wah becomes public, beginning at Ṣafā with his own family named first." },
      { day: 188, title: "Abū Lahab's Rejection", ref: "Q 111:1–5", note: "An uncle's public curse answered directly by name in revelation — family opposition at its sharpest." },
      { day: 189, title: "Quraysh Mock and Threaten", ref: "Seerah", note: "Ridicule tried first, as the lowest-cost weapon available to men still unsure how serious this was." },
      { day: 190, title: "\"Say: He Is Allah, One\"", ref: "Q 112:1–4", note: "Tawḥīd restated plainly against every accusation of ancestry, sonship, or partnership." },
      { day: 191, title: "Torture of the Weak and Enslaved", ref: "Seerah", note: "Bilāl, 'Ammār, and his mother Sumayyah bear the earliest and harshest physical persecution." },
      { day: 192, title: "\"Aḥad, Aḥad\"", ref: "Seerah", note: "Bilāl's endurance under a scorching stone in the desert — one word repeated as an anchor." },
      { day: 193, title: "Offers of Wealth, Kingship, and Compromise", ref: "Seerah", note: "\"Even if they put the sun in my right hand and the moon in my left, I would not abandon this.\"" },
      { day: 194, title: "Abū Ṭālib's Protection Without Belief", ref: "Seerah", note: "Shielding his nephew from Quraysh's demands while never accepting the message himself." },
      { day: 195, title: "First Migration to Abyssinia", ref: "Seerah", note: "A small group sent to safety under a Christian king, escaping persecution without abandoning the mission." },
      { day: 196, title: "Ja'far's Speech Before the Negus", ref: "Seerah", note: "\"We were a people of ignorance...\" — the clearest early summary of what Islam actually changed." },
      { day: 197, title: "The Negus Weeps Over the Qur'an", ref: "Seerah", note: "Sūrah Maryam recited in a foreign court, and a king recognizes its source." },
      { day: 198, title: "'Umar ibn al-Khaṭṭāb's Conversion", ref: "Seerah", note: "One of Islam's fiercest opponents becomes one of its most decisive protectors." },
      { day: 199, title: "The Boycott of Banū Hāshim Begins", ref: "Seerah", note: "Economic and social exclusion imposed on the Prophet's entire clan, believers and non-believers alike." },
      { day: 200, title: "Three Years in Shi'b Abī Ṭālib", ref: "Seerah", note: "Confinement to a narrow valley, hunger endured, and faith that did not break." },
      { day: 201, title: "The Document Eaten by Termites", ref: "Seerah", note: "A sign given exactly as the boycott document is examined — its terms already unraveling." },
      { day: 202, title: "The Year of Sorrow — Khadījah's Death", ref: "Seerah", note: "The loss of a lifelong source of comfort and support, at the hardest possible moment." },
      { day: 203, title: "Abū Ṭālib's Death", ref: "Seerah", note: "Protection withdrawn just as persecution needed to be met without it." },
      { day: 204, title: "The Journey to Ṭā'if", ref: "Seerah", note: "Seeking support elsewhere, and instead met with mockery and stones." },
      { day: 205, title: "\"O Allah, to You I Complain\"", ref: "Seerah (the du'ā' of Ṭā'if)", note: "Total honesty addressed to Allah alone, in the depths of public rejection." },
      { day: 206, title: "The Angel of the Mountains", ref: "Seerah", note: "Offered the power to crush Ṭā'if between two mountains — and choosing mercy instead." },
      { day: 207, title: "'Addās the Christian Servant", ref: "Seerah", note: "One quiet, unexpected conversion inside a scene otherwise defined by rejection." },
      { day: 208, title: "Returning to Makkah Under Protection", ref: "Seerah", note: "Muṭ'im ibn 'Adī's guarantee allows re-entry to a city that had just driven him out." },
      { day: 209, title: "The Night Journey Begins", ref: "Q 17:1", note: "\"Glory be to He who took His servant by night\" — al-Isrā' opens with a single, total statement." },
      { day: 210, title: "Al-Masjid al-Aqṣā", ref: "Seerah", note: "Leading every prophet before him in prayer — continuity with the whole story so far, made visible." },
      { day: 211, title: "The Ascension Through the Heavens", ref: "Seerah", note: "Meeting Ādam, 'Īsā, Mūsā, and Ibrāhīm, each in turn, on the way upward." },
      { day: 212, title: "Five Prayers Given as Fifty", ref: "Seerah", note: "Mūsā's repeated advice, and mercy reducing an impossible burden down to something bearable." },
      { day: 213, title: "Abū Bakr, \"aṣ-Ṣiddīq\"", ref: "Seerah", note: "Believing the account without hesitation the next morning — a title earned in a single sentence." },
      { day: 214, title: "Meeting Pilgrims From Yathrib", ref: "Seerah", note: "Six men encountered at 'Aqabah hear the message for the first time and carry it home." },
      { day: 215, title: "The First Pledge of 'Aqabah", ref: "Seerah", note: "Twelve individuals pledge to core moral commitments — the earliest formal step toward Madīnah." },
      { day: 216, title: "Muṣ'ab ibn 'Umayr Sent to Teach", ref: "Seerah", note: "Islam's first appointed teacher-ambassador, sent to a city not yet his own." },
      { day: 217, title: "Sa'd ibn Mu'ādh's Conversion", ref: "Seerah", note: "A tribal leader's opposition dissolves in the course of one conversation." },
      { day: 218, title: "The Second Pledge of 'Aqabah", ref: "Seerah", note: "Seventy-three pledge to defend the Prophet as they would their own families." },
      { day: 219, title: "Permission to Emigrate", ref: "Seerah", note: "Muslims begin leaving Makkah quietly, in small groups, toward a city ready to receive them." },
      { day: 220, title: "The Plot to Kill Him", ref: "Q 8:30", note: "\"They plotted, and Allah planned — and Allah is the best of planners.\"" },
      { day: 221, title: "'Alī Sleeps in His Bed", ref: "Seerah", note: "Courage that bought the hours needed for a safe departure, at real personal risk." },
      { day: 222, title: "Leaving With Abū Bakr", ref: "Seerah", note: "Two companions, an uncertain road south before turning north, and total reliance on a plan kept secret." },
      { day: 223, title: "The Cave of Thawr", ref: "Q 9:40", note: "\"Do not grieve; indeed, Allah is with us\" — spoken with pursuers standing at the cave's very mouth." },
      { day: 224, title: "A Spider's Web and a Dove's Nest", ref: "Seerah", note: "Unseen protection at exactly the point human effort had run out." },
      { day: 225, title: "Surāqah ibn Mālik's Pursuit", ref: "Seerah", note: "A skilled tracker sent to capture them becomes, instead, a witness who later tells the story himself." },
      { day: 226, title: "Guided by 'Abdullāh ibn Uraiqiṭ", ref: "Seerah", note: "A trusted guide chosen for skill, despite not yet sharing the faith of those he led." },
      { day: 227, title: "Passing Through Qubā'", ref: "Seerah", note: "The very first mosque founded on the outskirts, before the journey's final stretch." },
      { day: 228, title: "Entering Yathrib", ref: "Seerah", note: "Children singing in the streets to welcome him — closing thirteen years of the Makkan mission." },
    ],
  },
  {
    id: 9,
    title: "Madinah — Community to Completion",
    range: "Days 229–328",
    dayStart: 229,
    dayEnd: 328,
    blurb: "Ten years that build an entire way of life from nothing: a mosque raised by hand, a charter binding tribes and faiths together, three great battles fought in defense, a treaty that looked like defeat and proved to be victory, and finally the return home to Makkah — ending in one sermon that completes the message.",
    tags: ["Sīrah","Madīnah","Badr","Uḥud","Ḥudaybiyyah","Fatḥ"],
    days: [
      { day: 229, title: "Building Masjid an-Nabawī", ref: "Seerah", note: "Physical labor shared by the Prophet himself alongside the poorest of his Companions." },
      { day: 230, title: "Living Quarters Beside the Mosque", ref: "Seerah", note: "Simplicity chosen deliberately over any comfort his new position might have allowed." },
      { day: 231, title: "Yathrib Becomes Madīnat an-Nabī", ref: "Seerah", note: "The city takes on a new identity, and a new center of gravity for the whole region." },
      { day: 232, title: "Brotherhood Between Muhājirūn and Anṣār", ref: "Seerah", note: "Homes and wealth shared freely between strangers now bound as family." },
      { day: 233, title: "The Constitution of Madīnah", ref: "Seerah", note: "A written charter uniting Muslims, Jewish tribes, and others under one shared civic framework." },
      { day: 234, title: "The Adhān Instituted", ref: "Seerah", note: "Bilāl's voice becomes the sound that now calls an entire city to prayer, five times a day." },
      { day: 235, title: "Facing Jerusalem in Prayer", ref: "Seerah", note: "The early qiblah maintained continuity with the prophets who came before." },
      { day: 236, title: "Illness Sweeps the New City", ref: "Seerah", note: "Abū Bakr and Bilāl fall sick with fever; a du'ā' of comfort is taught for exactly this hardship." },
      { day: 237, title: "Markets Rebuilt Free of Ribā", ref: "Seerah", note: "An economy re-founded on fairness, distinct from the practices Madīnah had known before." },
      { day: 238, title: "The Hypocrites of Madīnah Emerge", ref: "Q 2:8–10", note: "A new, quieter kind of opposition — belief claimed outwardly, doubt held inwardly." },
      { day: 239, title: "The Jewish Tribes of Madīnah", ref: "Seerah", note: "Banū Qaynuqā', an-Naḍīr, and Qurayẓah as neighbors under the terms of the shared charter." },
      { day: 240, title: "Fasting Ramaḍān Prescribed", ref: "Q 2:183–185", note: "\"That you may attain taqwā\" — a pillar of worship formally established." },
      { day: 241, title: "The Qiblah Changes to Makkah", ref: "Q 2:144", note: "Mid-prayer, in some accounts, the direction of every heart in the city turns at once." },
      { day: 242, title: "Zakāh Formalized", ref: "Q 9:60", note: "Charity structured into a clear system rather than left to individual discretion alone." },
      { day: 243, title: "Small Expeditions Begin", ref: "Seerah", note: "Early reconnaissance to understand Quraysh's caravan routes and intentions." },
      { day: 244, title: "The Caravan and the Coming Confrontation", ref: "Seerah", note: "Abū Sufyān changes route on hearing of Muslim interest, and a larger conflict becomes unavoidable." },
      { day: 245, title: "Marching Toward Badr", ref: "Seerah", note: "Three hundred and thirteen companions, lightly armed, set out with no illusions about the odds." },
      { day: 246, title: "\"If This Small Band Is Destroyed...\"", ref: "Seerah", note: "The Prophet's own du'ā' the night before battle, stripped of any false confidence." },
      { day: 247, title: "The Well of Badr", ref: "Seerah", note: "Securing the water source first — a tactical decision that shaped everything after it." },
      { day: 248, title: "Angels Sent as Reinforcement", ref: "Q 8:9", note: "\"I will support you with a thousand angels, in succession\" — help promised before the fighting starts." },
      { day: 249, title: "The Battle of Badr", ref: "Q 3:123", note: "Victory against overwhelming numerical odds, on the day the Qur'an calls \"the day of criterion.\"" },
      { day: 250, title: "Treatment of the Prisoners", ref: "Seerah", note: "Ransom for some, teaching literacy in exchange for freedom for others — mercy woven into victory." },
      { day: 251, title: "Grief and Gratitude After Badr", ref: "Q 8:17", note: "\"You did not kill them, but it was Allah who killed them\" — credit returned immediately to its source." },
      { day: 252, title: "Banū Qaynuqā' Break the Covenant", ref: "Seerah", note: "The first breach of the Madīnah charter, and the community's first internal test of that agreement." },
      { day: 253, title: "Family Life in Madīnah", ref: "Seerah", note: "Marriage to Ḥafṣah and the ordinary rhythms of a household built alongside extraordinary events." },
      { day: 254, title: "Between Two Battles", ref: "Seerah", note: "Quraysh's resolve to avenge Badr grows through the following year." },
      { day: 255, title: "One Year In — A Community Taking Root", ref: "Seerah", note: "The first full year in Madīnah closes with a fragile but functioning nation in place." },
      { day: 256, title: "Quraysh Return for Revenge", ref: "Seerah", note: "Three thousand march on Madīnah, determined to reverse the outcome of Badr." },
      { day: 257, title: "The Hypocrites Withdraw", ref: "Seerah", note: "'Abdullāh ibn Ubayy pulls back a third of the Muslim force before the fighting even begins." },
      { day: 258, title: "The Archers on the Hill", ref: "Q 3:152", note: "A defensive position whose discipline would decide the entire outcome of the battle." },
      { day: 259, title: "Turning Defeat Into a Lesson", ref: "Q 3:165–166", note: "\"Is it not that when a calamity struck you... you said, 'from where is this?'\" — asked directly, without softening it." },
      { day: 260, title: "The Prophet Wounded", ref: "Seerah", note: "A broken tooth, an injured face — and the mission continuing without pause." },
      { day: 261, title: "Ḥamzah's Martyrdom", ref: "Seerah", note: "\"The Lion of Allah\" falls at Uḥud, one of the community's most painful single losses." },
      { day: 262, title: "Women Who Fought and Nursed at Uḥud", ref: "Seerah", note: "Nusaybah bint Ka'b's defense of the Prophet at the height of the battle's danger." },
      { day: 263, title: "\"Do Not Weaken or Grieve\"", ref: "Q 3:139", note: "Consolation revealed directly in the aftermath, addressed to a shaken community." },
      { day: 264, title: "Ḥamrā' al-Asad — Pursuing the Wounded", ref: "Seerah", note: "Resolve shown by marching out again the very next day, injuries and all." },
      { day: 265, title: "Banū an-Naḍīr Expelled", ref: "Seerah", note: "A second violation of the Madīnah charter, resolved without bloodshed but with lasting consequence." },
      { day: 266, title: "Widows and Orphans Provided For", ref: "Q 4:2–3", note: "Inheritance and protection legislated directly in the aftermath of the community's losses." },
      { day: 267, title: "Marriages That Protected and Allied", ref: "Seerah", note: "Unions after Uḥud shaped as much by care for widows as by anything else." },
      { day: 268, title: "A Coalition of Enemies Gathers", ref: "Seerah", note: "Confederate tribes from across Arabia unite for a single, larger assault on Madīnah." },
      { day: 269, title: "Salmān al-Fārisī's Idea — the Trench", ref: "Seerah", note: "A defensive method unfamiliar to Arabia, adopted without hesitation because it worked." },
      { day: 270, title: "Digging the Khandaq Together", ref: "Seerah", note: "The Prophet labors beside the poorest of his Companions, not above them." },
      { day: 271, title: "Hunger Tied to the Stomach", ref: "Seerah", note: "A stone bound against hunger during the exhausting work of digging — endurance made visible." },
      { day: 272, title: "The Siege Tightens", ref: "Q 33:10–11", note: "\"When they came upon you from above you and from below you\" — pressure from every direction at once." },
      { day: 273, title: "Nu'aym ibn Mas'ūd's Quiet Diplomacy", ref: "Seerah", note: "Doubt sown carefully within the coalition, without a single blow struck." },
      { day: 274, title: "A Fierce Wind Scatters the Armies", ref: "Q 33:9", note: "\"We sent upon them a wind and armies you did not see\" — the siege ends without a decisive battle at all." },
      { day: 275, title: "Banū Qurayẓah's Betrayal", ref: "Seerah", note: "A third breach of the charter, this time during the height of the siege itself." },
      { day: 276, title: "Justice Delegated to Sa'd ibn Mu'ādh", ref: "Seerah", note: "Judgment entrusted to a leader both sides had reason to respect." },
      { day: 277, title: "A Dream of Pilgrimage", ref: "Seerah", note: "The Prophet sees himself completing 'Umrah in peace — a vision that will shape the next major decision." },
      { day: 278, title: "Setting Out Unarmed for 'Umrah", ref: "Seerah", note: "Fourteen hundred travel with the clear intention of worship, not conflict." },
      { day: 279, title: "'Uthmān Sent Into Makkah", ref: "Seerah", note: "Negotiation attempted on behalf of the pilgrims, at real personal risk to him." },
      { day: 280, title: "The Pledge of Riḍwān", ref: "Q 48:18", note: "Beneath a tree, the Companions pledge readiness to give their lives if it comes to that." },
      { day: 281, title: "The Hard Terms of Ḥudaybiyyah", ref: "Seerah", note: "A treaty whose conditions look, on the surface, like a clear loss for the Muslims." },
      { day: 282, title: "\"Have We Not Given You a Clear Victory?\"", ref: "Q 48:1", note: "Revelation reframes the treaty entirely, naming it a victory before its effects are even visible." },
      { day: 283, title: "Letters to Kings and Emperors", ref: "Seerah", note: "Invitations to Islam sent to Heraclius, Chosroes, the Negus, and al-Muqawqis." },
      { day: 284, title: "Khaybar's Fortresses", ref: "Seerah", note: "The northern frontier secured in the period the treaty had opened up." },
      { day: 285, title: "'Alī Given the Banner at Khaybar", ref: "Seerah", note: "\"One who loves Allah and His Messenger, and is loved by them\" — leadership entrusted by description, not just rank." },
      { day: 286, title: "Ṣafiyyah bint Ḥuyayy", ref: "Seerah", note: "A marriage that bridged a former conflict rather than simply ending it." },
      { day: 287, title: "The Fulfilled 'Umrah", ref: "Seerah", note: "A year later, the pilgrimage the earlier dream had promised is completed exactly as seen." },
      { day: 288, title: "Khālid ibn al-Walīd and 'Amr ibn al-'Āṣ Embrace Islam", ref: "Seerah", note: "Two future generals join the community, changing the shape of what follows." },
      { day: 289, title: "The Battle of Mu'tah", ref: "Seerah", note: "Facing the Byzantine frontier directly; three appointed commanders fall in succession." },
      { day: 290, title: "Khālid, \"The Sword of Allah\"", ref: "Seerah", note: "A disciplined, costly withdrawal that saves the remaining force from total loss." },
      { day: 291, title: "Banū Bakr Breaks the Ḥudaybiyyah Truce", ref: "Seerah", note: "An ally of Quraysh attacks Khuzā'ah, violating the treaty's core terms." },
      { day: 292, title: "Abū Sufyān's Failed Renewal Attempt", ref: "Seerah", note: "Traveling to Madīnah for reassurance and leaving without any given." },
      { day: 293, title: "Marching Toward Makkah in Secrecy", ref: "Seerah", note: "Ten thousand set out, and the city itself remains unaware until very late." },
      { day: 294, title: "'Abbās and Abū Sufyān in the Night", ref: "Seerah", note: "A former enemy's quiet, private surrender before the army's arrival." },
      { day: 295, title: "Amnesty Offered Before a Shot Is Fired", ref: "Seerah", note: "\"Whoever enters Abū Sufyān's house is safe\" — safety extended broadly, deliberately." },
      { day: 296, title: "Entering Makkah in Humility", ref: "Seerah", note: "Head lowered on his mount out of gratitude, not the posture of a conqueror." },
      { day: 297, title: "The Idols Fall", ref: "Q 17:81", note: "\"Truth has come, and falsehood has vanished\" — recited as the three hundred sixty idols are removed." },
      { day: 298, title: "\"Go — You Are Free\"", ref: "Seerah", note: "Forgiveness extended to the very people who had tortured and exiled him years earlier." },
      { day: 299, title: "The Adhān From Atop the Kaʿbah", ref: "Seerah", note: "Bilāl's voice heard exactly where idols had stood only hours before." },
      { day: 300, title: "Ḥunayn — Overconfidence Tested", ref: "Q 9:25–26", note: "\"On the day of Ḥunayn when your great numbers impressed you\" — a near-defeat born of misplaced confidence." },
      { day: 301, title: "Retreat, Then Standing Firm", ref: "Seerah", note: "The army rallies back around the Prophet at the critical moment." },
      { day: 302, title: "The Siege of Ṭā'if", ref: "Seerah", note: "The very city that once stoned him is now approached under very different circumstances." },
      { day: 303, title: "Distributing Wealth to Soften Hearts", ref: "Seerah", note: "Al-Mu'allafatu Qulūbuhum — generosity used deliberately to ease recent converts into the community." },
      { day: 304, title: "\"Would You Not Rather Have the Messenger?\"", ref: "Seerah", note: "An Anṣārī's question about the distribution answered with love, not defensiveness." },
      { day: 305, title: "Tabūk — Marching in Hardship", ref: "Q 9:41", note: "\"March forth, whether light or heavy\" — the most physically demanding expedition of his life." },
      { day: 306, title: "Those Who Stayed Behind", ref: "Q 9:118", note: "Ka'b ibn Mālik's forty days of social isolation, and the mercy that eventually ends it." },
      { day: 307, title: "The Delegations Arrive — 'Ām al-Wufūd", ref: "Seerah", note: "Tribes from across Arabia send representatives to embrace Islam, one after another." },
      { day: 308, title: "\"When Comes the Help of Allah\"", ref: "Q 110:1–3", note: "Sūrah an-Naṣr revealed — a mission visibly nearing its completion." },
      { day: 309, title: "Disavowal of the Idolaters Proclaimed", ref: "Q 9:1–5", note: "Sūrah at-Tawbah's terms announced publicly, closing the door on old arrangements with idolatry." },
      { day: 310, title: "The Christians of Najrān Visit Madīnah", ref: "Seerah", note: "Dialogue hosted directly in the mosque, without compulsion toward either side." },
      { day: 311, title: "Final Illness Draws Near", ref: "Seerah", note: "Weakness increases, though the mission's pace does not slow." },
      { day: 312, title: "Preparing for the Farewell Pilgrimage", ref: "Seerah", note: "A call goes out across Arabia, and vast numbers begin preparing to join him." },
      { day: 313, title: "Standing at 'Arafāt", ref: "Seerah", note: "Over one hundred thousand gathered in one place for the first and only time under his leadership." },
      { day: 314, title: "\"Your Blood and Wealth Are Sacred\"", ref: "Seerah (Khuṭbat al-Wadā')", note: "Human dignity and property affirmed as inviolable, stated in the plainest terms possible." },
      { day: 315, title: "\"No Arab Has Superiority Except by Piety\"", ref: "Seerah", note: "Equality declared openly, to the largest audience he ever addressed at once." },
      { day: 316, title: "Women's Rights Addressed", ref: "Seerah", note: "Kindness toward women commanded as a duty owed, not a favor granted." },
      { day: 317, title: "\"I Leave With You the Book of Allah\"", ref: "Seerah", note: "The two things named as what will keep the Ummah from straying after he is gone." },
      { day: 318, title: "\"This Day I Have Perfected Your Religion\"", ref: "Q 5:3", note: "Revealed at 'Arafāt itself — the completion of the message stated directly." },
      { day: 319, title: "\"Have I Not Conveyed the Message?\"", ref: "Seerah", note: "Witnessed by the entire multitude: \"O Allah, bear witness that I have.\"" },
      { day: 320, title: "Ghadīr Khumm and the Return Journey", ref: "Seerah", note: "Words of unity spoken on the road home, as the pilgrimage disperses." },
      { day: 321, title: "Growing Weakness in Madīnah", ref: "Seerah", note: "The final months, marked by increasing frailty alongside undiminished devotion." },
      { day: 322, title: "Usāmah's Army Prepared", ref: "Seerah", note: "Trust placed in a young commander even in these last, most demanding days." },
      { day: 323, title: "Leading Prayer for the Last Time", ref: "Seerah", note: "Abū Bakr asked to lead when illness finally overcomes him." },
      { day: 324, title: "\"O Allah, the Highest Companion\"", ref: "Seerah", note: "His final words, spoken quietly at the very end." },
      { day: 325, title: "The Twelfth of Rabī' al-Awwal", ref: "Seerah", note: "The Ummah's greatest single loss — a community left, for the first time, without him." },
      { day: 326, title: "Abū Bakr's Address", ref: "Seerah", note: "\"Whoever worshipped Muḥammad — Muḥammad is dead. Whoever worships Allah — Allah is alive, and does not die.\"" },
      { day: 327, title: "Burial in 'Ā'ishah's Chamber", ref: "Seerah", note: "Prophets are buried where they die — the simplest possible closing to an extraordinary life." },
      { day: 328, title: "What Remains When a Prophet Departs", ref: "Q 3:144", note: "\"Muḥammad is but a Messenger; messengers have passed on before him\" — the era closes exactly where the Qur'an itself frames it." },
    ],
  },
  {
    id: 10,
    title: "The Rightly-Guided Caliphs",
    range: "Days 329–350",
    dayStart: 329,
    dayEnd: 350,
    blurb: "The story does not end at the grave — this is the \"vice versa\": how the Ummah, suddenly without its Prophet, held together, survived rebellion, preserved the Qur'an in written form, expanded rapidly, and was tested by its own internal grief, across thirty years carried by four of his closest Companions.",
    tags: ["Khulafā'","Abū Bakr","'Umar","'Uthmān","'Alī"],
    days: [
      { day: 329, title: "Saqīfah Banī Sā'idah", ref: "History", note: "A successor chosen amid raw grief — Abū Bakr selected by consensus in the community's most fragile hour." },
      { day: 330, title: "\"I Am Not the Best of You\"", ref: "History", note: "Abū Bakr's inaugural address — leadership framed as accountability, not superiority." },
      { day: 331, title: "The Wars of Apostasy (Riddah)", ref: "History", note: "Holding the Ummah together as several tribes withdraw allegiance immediately after the Prophet's death." },
      { day: 332, title: "Musaylimah the Liar Defeated", ref: "History", note: "The Battle of Yamāmah — a serious, costly threat to the young community's unity." },
      { day: 333, title: "Compiling the Qur'an in Written Form", ref: "History", note: "Zayd ibn Thābit's task, urgently commissioned after many huffaz are lost at Yamāmah." },
      { day: 334, title: "Continuity Secured Deliberately", ref: "History", note: "Abū Bakr's final days, and 'Umar's appointment prepared before it could become a crisis." },
      { day: 335, title: "'Umar ibn al-Khaṭṭāb — al-Fārūq", ref: "History", note: "Justice carried out so visibly that it became legendary even among his opponents." },
      { day: 336, title: "The Conquest of Jerusalem", ref: "History", note: "'Umar enters on foot, and personally guarantees the safety and worship of the city's inhabitants." },
      { day: 337, title: "The Islamic Calendar Established", ref: "History", note: "The Hijrah itself is chosen as year one — the migration, not a battle, marks the new era." },
      { day: 338, title: "Building Institutions of Governance", ref: "History", note: "Dīwān, courts, and public welfare systems — a state built, not only an army maintained." },
      { day: 339, title: "'Umar's Assassination", ref: "History", note: "Struck while leading prayer in the mosque; a shūrā convened immediately to choose his successor." },
      { day: 340, title: "'Uthmān ibn 'Affān — Dhū'n-Nūrayn", ref: "History", note: "Modesty and extraordinary personal generosity define the early years of his leadership." },
      { day: 341, title: "The Qur'an Standardized", ref: "History", note: "The 'Uthmānic muṣḥaf — one written recitation preserved and distributed for every future generation." },
      { day: 342, title: "Expansion and Its Growing Pains", ref: "History", note: "Rapid growth brings prosperity, and with it, new political and social tensions." },
      { day: 343, title: "The Siege of 'Uthmān's House", ref: "History", note: "Martyred while reciting the Qur'an in his own home — the community's unity tested severely." },
      { day: 344, title: "'Alī ibn Abī Ṭālib — the Fourth Caliph", ref: "History", note: "Inheriting a fractured Ummah in the immediate aftermath of 'Uthmān's death." },
      { day: 345, title: "The Battle of the Camel", ref: "History", note: "Grief and disagreement among the Prophet's own closest Companions turn briefly to conflict." },
      { day: 346, title: "Ṣiffīn and the Arbitration", ref: "History", note: "A community tested by prolonged internal disagreement over how to respond to 'Uthmān's killing." },
      { day: 347, title: "The Khawārij Emerge", ref: "History", note: "Extremism born from misapplied zeal — a warning the later Ummah would return to often." },
      { day: 348, title: "'Alī's Assassination", ref: "History", note: "The Rāshidūn era's final loss, closing thirty years that began at Saqīfah." },
      { day: 349, title: "What \"Rightly-Guided\" Means", ref: "History", note: "Roughly thirty years fulfilling a prophecy about the era to follow prophethood directly." },
      { day: 350, title: "The Chain Carried Forward", ref: "Q 33:40", note: "\"Seal of the Prophets\" — yet the message itself entrusted onward, carried by the Ummah rather than a new messenger." },
    ],
  },
  {
    id: 11,
    title: "Living the Inheritance",
    range: "Days 351–365",
    dayStart: 351,
    dayEnd: 365,
    blurb: "The final two weeks fold the whole 365-day arc back into the reader's own life — the same Tawḥīd declared on Day 1, now carried forward by someone who has walked the entire road to reach it again.",
    tags: ["Reflection","Closing"],
    days: [
      { day: 351, title: "One Ummah, Many Generations", ref: "Q 3:110", note: "\"You are the best nation raised up for mankind\" — read as an ongoing responsibility, not a finished achievement." },
      { day: 352, title: "The Qur'an as Living Guidance", ref: "Q 15:9", note: "\"We have sent down the message, and We will preserve it\" — not a historical record, but a book still speaking." },
      { day: 353, title: "The Seerah as a Mirror", ref: "Reflection", note: "Every trial in this 365-day story has some echo in an ordinary life today." },
      { day: 354, title: "Carrying Tawḥīd Forward", ref: "Q 21:25", note: "Returning to Day 1's truth, now understood through everything walked between here and there." },
      { day: 355, title: "What Ādam Teaches About Returning", ref: "Reflection", note: "Tawbah as a lifelong companion, not a one-time event." },
      { day: 356, title: "What Ibrāhīm Teaches About Standing Alone", ref: "Reflection", note: "Conviction that does not require a crowd's agreement to be correct." },
      { day: 357, title: "What Yūsuf Teaches About Betrayal", ref: "Reflection", note: "Patience that ends in forgiveness rather than resentment." },
      { day: 358, title: "What Mūsā Teaches About Facing Power", ref: "Reflection", note: "Gentleness in method even when the cause is entirely just." },
      { day: 359, title: "What Maryam Teaches About the Unseen", ref: "Reflection", note: "Trust held through isolation, pain, and public accusation, without complaint to people." },
      { day: 360, title: "What the Sīrah Teaches About Gentleness", ref: "Reflection", note: "Da'wah offered as invitation across fifty-three years, even to those who caused the most harm." },
      { day: 361, title: "What Badr Teaches About Reliance", ref: "Reflection", note: "Full preparation, followed by full trust in an outcome only Allah controls." },
      { day: 362, title: "What Ḥudaybiyyah Teaches About Apparent Loss", ref: "Reflection", note: "Accepting hard terms with patience, and letting time reveal what they were actually worth." },
      { day: 363, title: "What the Farewell Sermon Asks of You", ref: "Reflection", note: "Justice, equality, and kindness — named as personal duties, not abstract ideals." },
      { day: 364, title: "\"This Day I Have Perfected Your Religion\" — Revisited", ref: "Q 5:3", note: "The same verse from Day 318, read again now that the whole story stands behind it." },
      { day: 365, title: "The Journey Continues", ref: "Q 2:286", note: "\"Allah does not burden a soul beyond what it can bear\" — closing where Sabil always closes: return gently. The story is not behind you. You are living its next page." },
    ],
  },
];

export const SEERAH_PLAN_TOTAL_DAYS = 365;
